services:
    .:
        build:
            context: ./.
        ports:
            - 5000:5000
    front-end:
        build:
            context: ./front-end
        environment:
            NODE_ENV: production
        ports:
            - 3000:3000
